CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:service}-user-pool-${self:provider.stage}
    UsernameAttributes:
      - email
    AutoVerifiedAttributes:
      - email
    MfaConfiguration: OPTIONAL
    EnabledMfas:
      - SOFTWARE_TOKEN_MFA
    Policies:
      PasswordPolicy:
        MinimumLength: 12
        RequireUppercase: true
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: true
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    EmailConfiguration:
      EmailSendingAccount: COGNITO_DEFAULT
    DeviceConfiguration:
      ChallengeRequiredOnNewDevice: true
      DeviceOnlyRememberedOnUserPrompt: false

CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:service}-user-pool-client-${self:provider.stage}
    UserPoolId: !Ref CognitoUserPool
    RefreshTokenValidity: 30
    AccessTokenValidity: 1
    IdTokenValidity: 1
    TokenValidityUnits:
      AccessToken: hours
      IdToken: hours
      RefreshToken: days
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - email
      - openid
      - profile
    SupportedIdentityProviders:
      - COGNITO
    AllowedOAuthFlows:
      - code
      - implicit
    ExplicitAuthFlows:
      - ALLOW_USER_SRP_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    PreventUserExistenceErrors: ENABLED
    EnableTokenRevocation: true
    CallbackURLs:
      - ${self:custom.callbackUrls.${self:provider.stage}}
    LogoutURLs:
      - ${self:custom.logoutUrls.${self:provider.stage}}
    DefaultRedirectURI: ${self:custom.callbackUrls.${self:provider.stage}}

CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    Domain: !Sub '${AWS::StackName}-${AWS::AccountId}'
    UserPoolId: !Ref CognitoUserPool